"""Миграции обратимы и совпадают с моделями.

Идёт в отдельной базе `<имя>_test_migrations`, чтобы не трогать базу,
на которой работают остальные тесты.
"""

import pytest
from alembic.util.exc import AutogenerateDiffsDetected
from conftest import _test_database_url, recreate_database, run_alembic

from ocmanager.core.config import Settings

pytestmark = pytest.mark.db


async def test_upgrade_check_downgrade_upgrade(settings: Settings) -> None:
    url = _test_database_url(settings.database_url, "_migrations")
    await recreate_database(url)
    await run_alembic(url, "upgrade", "head")
    try:
        await run_alembic(url, "check")
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"модели разошлись с миграциями — нужна новая ревизия:\n{exc}")
    await run_alembic(url, "downgrade", "base")
    await run_alembic(url, "upgrade", "head")
