"""clients_plans

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-28 22:56:57.010025+00:00
"""

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("trial_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lang IN ('ru', 'en')", name=op.f("ck_clients_lang")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_clients_telegram_id")),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("device_limit", sa.Integer(), nullable=False),
        sa.Column("traffic_limit_bytes", sa.BigInteger(), nullable=True),
        sa.Column("speed_limit_kbps", sa.Integer(), nullable=True),
        sa.Column("price_amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column(
            "provider_product_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_trial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("device_limit > 0", name=op.f("ck_plans_device_limit")),
        sa.CheckConstraint("duration_days > 0", name=op.f("ck_plans_duration_days")),
        sa.CheckConstraint("price_amount >= 0", name=op.f("ck_plans_price_amount")),
        sa.CheckConstraint(
            "traffic_limit_bytes IS NULL OR traffic_limit_bytes > 0",
            name=op.f("ck_plans_traffic"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    op.create_index(
        "uq_plans_single_trial",
        "plans",
        ["is_trial"],
        unique=True,
        postgresql_where=sa.text("is_trial"),
    )
    # ### end Alembic commands ###
    # Скрытый тариф пробного периода: сервис не работает без него.
    # Длительность и трафик при старте trial берутся из RuntimeSettings.
    op.execute(
        sa.text(
            "INSERT INTO plans (code, name_i18n, duration_days, device_limit, price_amount,"
            " currency, is_active, is_trial)"
            " VALUES ('trial', CAST(:name AS jsonb), 3, 1, 0, 'RUB', false, true)"
        ).bindparams(name=json.dumps({"ru": "Пробный период", "en": "Trial"}, ensure_ascii=False))
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_plans_single_trial",
        table_name="plans",
        postgresql_where=sa.text("is_trial"),
    )
    op.drop_table("plans")
    op.drop_table("clients")
    # ### end Alembic commands ###
