"""subscriptions

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-29 12:41:22.173345+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "plan_is_trial",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("device_limit", sa.Integer(), nullable=False),
        sa.Column("traffic_limit_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "traffic_used_bytes",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("traffic_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("external_subscription_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending_payment', 'trial', 'active', 'expired', 'exhausted',"
            " 'cancelled', 'blocked')",
            name=op.f("ck_subscriptions_status"),
        ),
        sa.CheckConstraint("device_limit > 0", name=op.f("ck_subscriptions_device_limit")),
        sa.CheckConstraint("traffic_used_bytes >= 0", name=op.f("ck_subscriptions_traffic_used")),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_subscriptions_client_id_clients"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_subscriptions_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("client_id", name=op.f("uq_subscriptions_client_id")),
    )
    op.create_index(
        "ix_subscriptions_live_expiry",
        "subscriptions",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('trial', 'active', 'cancelled')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_subscriptions_live_expiry",
        table_name="subscriptions",
        postgresql_where=sa.text("status IN ('trial', 'active', 'cancelled')"),
    )
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
