"""devices

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 12:58:33.211620+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("ocserv_username", sa.String(), nullable=False),
        sa.Column("cert_serial", sa.String(), nullable=False),
        sa.Column("cert_fingerprint", sa.String(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cert_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('ios', 'android', 'windows', 'macos', 'linux')",
            name=op.f("ck_devices_platform"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_devices_client_id_clients")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("cert_serial", name=op.f("uq_devices_cert_serial")),
        sa.UniqueConstraint("client_id", "seq", name="uq_devices_client_id_seq"),
        sa.UniqueConstraint("ocserv_username", name=op.f("uq_devices_ocserv_username")),
    )
    op.create_index("ix_devices_client_id", "devices", ["client_id"], unique=False)
    op.create_table(
        "revocations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("device_id", sa.BigInteger(), nullable=False),
        sa.Column("cert_serial", sa.String(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_revocations_device_id_devices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revocations")),
        sa.UniqueConstraint("device_id", name=op.f("uq_revocations_device_id")),
    )
    op.create_index(
        "ix_revocations_pending",
        "revocations",
        ["id"],
        unique=False,
        postgresql_where=sa.text("applied_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_revocations_pending",
        table_name="revocations",
        postgresql_where=sa.text("applied_at IS NULL"),
    )
    op.drop_table("revocations")
    op.drop_index("ix_devices_client_id", table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
