"""traffic

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-28 23:13:03.569487+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("ocserv_session_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_ip", sa.String(), nullable=True),
        sa.Column("vpn_ip", sa.String(), nullable=True),
        sa.Column("bytes_in", sa.BigInteger(), nullable=False),
        sa.Column("bytes_out", sa.BigInteger(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("final_received", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_session_log_node_id_nodes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_log")),
        sa.UniqueConstraint(
            "node_id", "ocserv_session_id", "started_at", name="uq_session_log_node_session"
        ),
    )
    op.create_index(
        "ix_session_log_open",
        "session_log",
        ["node_id"],
        unique=False,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_index(
        "ix_session_log_username", "session_log", ["username", "started_at"], unique=False
    )
    op.create_table(
        "traffic_daily",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("bytes_in", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("bytes_out", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("duration_sec", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_traffic_daily_node_id_nodes")
        ),
        sa.PrimaryKeyConstraint("username", "node_id", "day", name=op.f("pk_traffic_daily")),
    )
    op.create_table(
        "traffic_samples",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bytes_in_delta", sa.BigInteger(), nullable=False),
        sa.Column("bytes_out_delta", sa.BigInteger(), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_traffic_samples_node_id_nodes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traffic_samples")),
    )
    op.create_index("ix_traffic_samples_ts", "traffic_samples", ["ts"], unique=False)
    op.create_index(
        "ix_traffic_samples_username_ts", "traffic_samples", ["username", "ts"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_traffic_samples_username_ts", table_name="traffic_samples")
    op.drop_index("ix_traffic_samples_ts", table_name="traffic_samples")
    op.drop_table("traffic_samples")
    op.drop_table("traffic_daily")
    op.drop_index("ix_session_log_username", table_name="session_log")
    op.drop_index(
        "ix_session_log_open",
        table_name="session_log",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_table("session_log")
    # ### end Alembic commands ###
