"""checkout_intents

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-02 09:08:30.483880+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkout_intents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_checkout_intents_client_id_clients")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_checkout_intents_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkout_intents")),
    )
    op.create_index(
        "ix_checkout_intents_client_created",
        "checkout_intents",
        ["client_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_checkout_intents_client_created", table_name="checkout_intents")
    op.drop_table("checkout_intents")
    # ### end Alembic commands ###
