"""outbox_messages

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-02 15:29:53.217508+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("recipient_type", sa.String(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("template_key", sa.String(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("send_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.CheckConstraint("lang IN ('ru', 'en')", name=op.f("ck_outbox_messages_lang")),
        sa.CheckConstraint(
            "recipient_type IN ('client', 'admin')", name=op.f("ck_outbox_messages_recipient_type")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'failed', 'undeliverable')",
            name=op.f("ck_outbox_messages_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint("chat_id", "dedupe_key", name="uq_outbox_messages_chat_id_dedupe_key"),
    )
    op.create_index(
        "ix_outbox_messages_pending",
        "outbox_messages",
        ["send_after", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_messages_pending",
        table_name="outbox_messages",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
